require "English"
require "gemdiff/version"
require "gemdiff/colorize"
require "gemdiff/cli"
require "gemdiff/bundle_inspector"
require "gemdiff/outdated_gem"
require "gemdiff/repo_finder"
require "gemdiff/gem_updater"
